--- # Master playbook to launch server on ec2

- name: Launch an EC2 instance on AWS
  hosts: local
  user: test
  become: yes
  become_method: sudo
  connection: ssh
  vars:
    - instance_type: t1.micro
    - image: ami-9dbea4fc
    - region: "{{ ec2_region }}"
  vars_files:
    - "/home/test/secure.yml"
  roles:
    - ec2
