--- # My first YAML playbook for Ansible
- hosts: local
  user: test
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: web_domain
      prompt: Web Domain
  tasks:
    - name: Install Apache Web Server
      action: apt name=apache2 state=installed
      notify: Restart apache2
  handlers:
    - name: Restart apache2
      action: service name=apache2 state=restarted
